(library
 (name protocol_emulator_test)
 (libraries
  core
  hardcaml
  protocol_emulator
  hardcaml_test_harness
  hardcaml_waveterm
  hardcaml_verify
  re
  hardcaml_hobby_boards
  ppxlib
  ppx_firmware)
 (preprocess
  (pps ppx_hardcaml ppx_jane ppx_firmware))
 (inline_tests
  (deps
   (glob_files *.asm)
   (glob_files assemble/*.asm)
   (glob_files *.hex)
   ../formal/Makefile
   ../src/protocol_emulator.v)
  (flags
   (-source-tree-root .))))
