open! Core
open! Hardcaml
open Protocol_emulator
open Protocol_emulator_test

(* A UART receiver's tolerance on the RTL, every frame of a stream by induction on frames.
   The sender runs free at m 2^-16 cycles a bit from any phase, as Tolerance models it and
   engine 1's fractional period sends; the bytes, m within the bounds and the start are
   free. The word the host reads is the byte sent, with no irq and no fault, and the next
   frame's start edge, right behind the stop bit, is captured as far after the first's as
   it comes, so the next frame meets the receiver as the first did, at another phase,
   which the proof already covers. With m a step past either bound, or the receiver's
   sample point a cycle late at the bounds of the one on time, a run has to fail. *)

module Firmware = struct
  type t =
    { receiver : Tolerance.Receiver.t
    ; moved : Tolerance.Receiver.t (** Every read a cycle later. *)
    ; label : string
    }

  let replace_exn source ~pattern ~with_ =
    let moved = String.substr_replace_first source ~pattern ~with_ in
    if String.equal moved source
    then raise_s [%message "BUG: no sample point to move" pattern];
    moved
  ;;

  let uart_rx ~period =
    let source = Uart.rx ~period in
    let half = (period / 2) - 1 in
    { receiver = Tolerance.Receiver.uart_rx ~period ()
    ; moved =
        Tolerance.Receiver.uart_rx
          ~source:
            (replace_exn
               source
               ~pattern:[%string "set y, %{half#Int}\n"]
               ~with_:[%string "set y, %{half + 1#Int}\n"])
          ~period
          ()
    ; label = [%string "uart_rx at %{period#Int} cycles a bit"]
    }
  ;;

  let uart_rx_host_rate ~half =
    { receiver = Tolerance.Receiver.uart_rx_host_rate ~half ()
    ; moved =
        Tolerance.Receiver.uart_rx_host_rate
          ~source:
            (replace_exn
               Uart.rx_host_rate
               ~pattern:"    sub t, 1"
               ~with_:"    nop                     ")
          ~half
          ()
    ; label = [%string "uart_rx_host_rate at a half period of %{half#Int}"]
    }
  ;;
end

let rom words =
  List.mapi words ~f:(fun a w -> sprintf "      %d: rom = 16'h%04x;" a w)
  |> String.concat ~sep:"\n"
;;

let config_ports (config : Program_config.t) =
  Engine.Config.(
    to_list
      (map2 port_names (of_program_config config) ~f:(fun name bits ->
         [%string
           ".config$%{name}(%{Bits.width bits#Int}'d%{Bits.to_unsigned_int bits#Int})"])))
  |> String.concat ~sep:",\n    "
;;

let ceil_div a b = (a + b - 1) / b

let write (firmware : Firmware.t) ~moved =
  let receiver = if moved then firmware.moved else firmware.receiver in
  let program = Asm.assemble receiver.firmware.source |> ok_exn in
  let config = Asm.Program.configure program receiver.firmware.config in
  let words = Asm.Program.words program |> ok_exn in
  let bounds = Tolerance.bounds firmware.receiver in
  let own = Tolerance.bounds receiver in
  let host =
    match receiver.preload with
    | [] -> "1'b0", "16'd0"
    | [ word ] -> "cycle == 2", [%string "16'd%{word#Int}"]
    | _ -> raise_s [%message "BUG: one host word at most"]
  in
  let tx_valid, tx_value = host in
  let what = if moved then ", its sample point a cycle late" else "" in
  let own_range =
    if moved
    then [%string "; this one's own, %{own.least#Int} to %{own.most#Int}"]
    else ""
  in
  let pin = config.in_base in
  (* the receiver is waiting for a start bit by then, with or without a host word *)
  let begin_at = 16 in
  let slowest = Int.max bounds.most own.most + 1 in
  let done_at = begin_at + 7 + ceil_div (10 * slowest) Tolerance.unit + 8 in
  [%string
    {|// Generated by test/certify/write_tolerance.exe: %{firmware.label}%{what},
// on the RTL, a frame and the next one's start edge from a sender at m 2^-16 cycles a
// bit, any phase. Bounds from its certificate: m from %{bounds.least#Int} to %{bounds.most#Int}%{own_range}.
module tolerance (input clk);
  (* anyconst *) reg [7:0] byte_0, byte_1;
  (* anyconst *) reg [31:0] m;
  (* anyconst *) reg [15:0] phase;
  (* anyconst *) reg [2:0] delay;

  always @(*)
`ifdef FASTER
    assume (m == %{own.least - 1#Int});
`elsif SLOWER
    assume (m == %{own.most + 1#Int});
`elsif OWN
    assume (m >= %{own.least#Int} && m <= %{own.most#Int});
`else
    assume (m >= %{bounds.least#Int} && m <= %{bounds.most#Int});
`endif

  function [15:0] rom(input [8:0] a);
    case (a)
%{rom words}
      default: rom = 0;
    endcase
  endfunction

  reg [9:0] cycle = 0;
  always @(posedge clk) if (cycle != 1023) cycle <= cycle + 10'd1;
  wire clear = cycle == 0;
  wire start = cycle == 1;

  // bit k of two frames back to back shows from cycle n0 + (phase + k * m) / 2^16 on;
  // the second's start bit, bit 10, from e2
  wire [9:0] n0 = %{begin_at#Int} + delay;
  reg [9:0] e2 = 0;
  // idle high past the second stop bit, to the end of k's range
  wire [31:0] frames = {12'hfff, byte_1, 1'b0, 1'b1, byte_0, 1'b0};
  reg [4:0] k = 0;
  reg [32:0] acc = 0;
  wire [32:0] next_acc = acc - 33'd%{Tolerance.unit#Int};
  always @(posedge clk)
    if (cycle < n0) begin
      k <= 0;
      acc <= phase + m;
    end else if (next_acc < 33'd%{Tolerance.unit#Int}) begin
      k <= k == 31 ? k : k + 5'd1;
      acc <= next_acc + m;
      if (k == 9) e2 <= cycle + 10'd1;
    end else
      acc <= next_acc;
  wire line = cycle < n0 || frames[k];

  wire [8:0] sram_addr;
  reg [15:0] fetched;
  always @(posedge clk) fetched <= rom(sram_addr);
  wire [3:0] rx_level;
  wire [15:0] rx_head;
  wire [23:0] capture;
  wire irq, faulted;
  wire pop = cycle >= 2 && rx_level != 0;
  engine_top dut (
    .clock(clk), .clear(clear),
    %{config_ports config},
    .start(start), .program_write$valid(1'b0), .program_write$addr(9'b0),
    .program_write$data(16'b0), .data_write$valid(1'b0), .data_write$addr(9'b0),
    .data_write$data(16'b0), .tx$valid(%{tx_valid}), .tx$value(%{tx_value}), .rx_pop(pop),
    .clear_irq(1'b0), .stop(1'b0), .flush(1'b0),
    .inputs({27'b0, line} << %{pin#Int}), .sram_addr(sram_addr), .sram_dout(fetched),
    .data_sram_dout(16'b0), .irq(irq), .faulted(faulted), .rx_level(rx_level),
    .rx_head(rx_head), .capture(capture));

  reg [1:0] pops = 0;
  always @(posedge clk) if (pop && pops != 3) pops <= pops + 2'd1;

  // each capture the receiver takes, the first and the count of them
  reg [23:0] last_capture = 0, first_capture = 0;
  reg [1:0] captures = 0;
  wire captured = cycle >= 2 && capture != last_capture;
  always @(posedge clk) begin
    last_capture <= capture;
    if (captured && captures != 3) captures <= captures + 2'd1;
    if (captured && captures == 0) first_capture <= capture;
  end

  // the word the host reads is the byte sent, nothing goes wrong, and the second start
  // edge is captured as far after the first as it shows
  always @(*)
    if (cycle >= 2) begin
      assert (!irq && !faulted);
      if (pop) assert (pops == 0 && rx_head == {8'b0, byte_0});
      if (captured && captures == 1) assert (capture - first_capture == {14'b0, e2 - n0});
      if (cycle >= %{done_at#Int}) assert (pops == 1 && captures == 2);
    end

  // a run at each bound gets there, so the claims above are not vacuous: these have to
  // fail
`ifdef REACH_LEAST
  always @(*)
    if (m == %{own.least#Int}) assert (!(cycle >= %{done_at#Int} && pops == 1 && captures == 2));
`endif
`ifdef REACH_MOST
  always @(*)
    if (m == %{own.most#Int}) assert (!(cycle >= %{done_at#Int} && pops == 1 && captures == 2));
`endif
endmodule
|}]
;;

(* The SPI target in mode 0 under a controller whose every SCK phase is free from [active]
   or [idle] cycles to [slack] more, each on its own, the setup from CS too: two bytes,
   MOSI moving on SCK's falling edge in the cycle it falls. The target follows the clock,
   so no rate error builds up; what it needs is the phases this long. FASTER takes one
   cycle off the shortest active phase, SLOWER off the shortest idle one. *)
let write_spi ~active ~idle ~slack =
  let mode = Spi_cs.Mode.of_int 0 in
  let pins = Spi_target.pads in
  let program = Asm.assemble (Spi_target.firmware ~mode pins) |> ok_exn in
  let config = Asm.Program.configure program (Spi_target.config pins) in
  let words = Asm.Program.words program |> ok_exn in
  let begin_at = 40 in
  let done_at = begin_at + active + slack + (16 * (active + idle + (2 * slack))) + 16 in
  [%string
    {|// Generated by test/certify/write_tolerance.exe: the SPI target in mode 0 on the RTL,
// two bytes from a controller whose SCK phases are each free from %{active#Int} cycles high or
// %{idle#Int} low to %{slack#Int} more.
module tolerance (input clk);
  (* anyconst *) reg [7:0] byte_0, byte_1;
  (* anyseq *) wire [4:0] choice;
  always @(*) assume (choice <= %{slack#Int});
`ifdef FASTER
  localparam active = %{active - 1#Int};
`else
  localparam active = %{active#Int};
`endif
`ifdef SLOWER
  localparam idle = %{idle - 1#Int};
`else
  localparam idle = %{idle#Int};
`endif

  function [15:0] rom(input [8:0] a);
    case (a)
%{rom words}
      default: rom = 0;
    endcase
  endfunction

  reg [9:0] cycle = 0;
  always @(posedge clk) if (cycle != 1023) cycle <= cycle + 10'd1;
  wire clear = cycle == 0;
  wire start = cycle == 1;

  // the controller: deselected, then CS low for a setup, then each bit's high and low
  // phase, each its own length; 4 once the sixteenth bit's low phase is over
  localparam DESELECTED = 0, SETUP = 1, HIGH = 2, LOW = 3, DONE = 4;
  reg [2:0] state = DESELECTED;
  reg [6:0] left = 0;
  reg [3:0] b = 0;
  always @(posedge clk)
    if (cycle < %{begin_at#Int}) state <= DESELECTED;
    else if (state == DESELECTED) begin
      state <= SETUP;
      left <= active + choice;
    end else if (state != DONE && left > 1) left <= left - 7'd1;
    else if (state == SETUP) begin
      state <= HIGH;
      left <= active + choice;
    end else if (state == HIGH) begin
      state <= LOW;
      left <= idle + choice;
    end else if (state == LOW && b == 15) state <= DONE;
    else if (state == LOW) begin
      state <= HIGH;
      left <= active + choice;
      b <= b + 4'd1;
    end
  wire [15:0] bits = {byte_0, byte_1};
  wire cs = state == DESELECTED;
  wire sck = state == HIGH;
  // valid from the falling edge before a bit's rising one: the next bit while low
  wire mosi = state == LOW ? (b == 15 ? 1'b0 : bits[4'd14 - b]) : bits[4'd15 - b];

  wire [8:0] sram_addr;
  reg [15:0] fetched;
  always @(posedge clk) fetched <= rom(sram_addr);
  wire [3:0] rx_level;
  wire [15:0] rx_head;
  wire irq, faulted;
  wire pop = cycle >= 2 && rx_level != 0;
  engine_top dut (
    .clock(clk), .clear(clear),
    %{config_ports config},
    .start(start), .program_write$valid(1'b0), .program_write$addr(9'b0),
    .program_write$data(16'b0), .data_write$valid(1'b0), .data_write$addr(9'b0),
    .data_write$data(16'b0), .tx$valid(1'b0), .tx$value(16'd0), .rx_pop(pop),
    .clear_irq(1'b0), .stop(1'b0), .flush(1'b0),
    .inputs(({27'b0, cs} << %{pins.cs#Int}) | ({27'b0, sck} << %{pins.sck#Int})
      | ({27'b0, mosi} << %{pins.mosi#Int})),
    .sram_addr(sram_addr), .sram_dout(fetched),
    .data_sram_dout(16'b0), .irq(irq), .faulted(faulted), .rx_level(rx_level),
    .rx_head(rx_head));

  reg [1:0] pops = 0;
  always @(posedge clk) if (pop && pops != 3) pops <= pops + 2'd1;

  // each word the host reads is the byte sent, two by the end, and nothing goes wrong
  always @(*)
    if (cycle >= 2) begin
      assert (!irq && !faulted);
      if (pop) assert (pops < 2 && rx_head == {8'b0, pops == 0 ? byte_0 : byte_1});
      if (cycle >= %{done_at#Int}) assert (pops == 2);
    end

  // a run gets both words through, so the claims above are not vacuous: has to fail
`ifdef REACH_LEAST
  always @(*) assert (!(cycle >= %{done_at#Int} && pops == 2));
`endif
endmodule
|}]
;;

let spi_depth ~active ~idle ~slack =
  40 + active + slack + (16 * (active + idle + (2 * slack))) + 20
;;

(* -name NAME: uart_rx_N at N cycles a bit, or uart_rx_host_rate_N at half period N;
   -moved for the receiver with its sample point a cycle late; -depth for the steps the
   proof needs *)
let () =
  let args = Sys.get_argv () |> Array.to_list in
  let has flag = List.mem args flag ~equal:String.equal in
  let value flag ~default =
    match List.findi args ~f:(fun _ a -> String.equal a flag) with
    | Some (i, _) -> Int.of_string (List.nth_exn args (i + 1))
    | None -> default
  in
  let name =
    match List.findi args ~f:(fun _ a -> String.equal a "-name") with
    | Some (i, _) -> List.nth_exn args (i + 1)
    | None -> raise_s [%message "-name uart_rx_N or -name uart_rx_host_rate_N"]
  in
  let active = value "-active" ~default:14 in
  let idle = value "-idle" ~default:1 in
  let slack = value "-slack" ~default:4 in
  if String.equal name "spi_target_mode0"
  then (
    if has "-depth"
    then printf "%d\n" (spi_depth ~active ~idle ~slack)
    else print_string (write_spi ~active ~idle ~slack);
    exit 0);
  let firmware =
    match String.chop_prefix name ~prefix:"uart_rx_host_rate_" with
    | Some half -> Firmware.uart_rx_host_rate ~half:(Int.of_string half)
    | None ->
      (match String.chop_prefix name ~prefix:"uart_rx_" with
       | Some period -> Firmware.uart_rx ~period:(Int.of_string period)
       | None -> raise_s [%message "no such receiver" name])
  in
  if has "-depth"
  then (
    let bounds = Tolerance.bounds firmware.receiver in
    let own = Tolerance.bounds firmware.moved in
    printf
      "%d\n"
      (16 + 7 + ceil_div (10 * (Int.max bounds.most own.most + 1)) Tolerance.unit + 12))
  else print_string (write firmware ~moved:(has "-moved"))
;;
