open! Core
open! Hardcaml
open Protocol_emulator
open Protocol_emulator_test

(* [Self_check.checker] on the core beside its contract, [Self_check_contract]: for any
   line, the irq rises only after a break of the contract, is up by the cycle the contract
   says, and no deadline of the checker's is missed. For one set of edges, and as far from
   the clear as formal/self_check.sby looks. *)

let max_inner = 9

module Contract = Self_check_contract.Make (struct
    let max_inner = max_inner
  end)

let pin = 0

let contract_verilog () =
  let scope = Scope.create ~flatten_design:true () in
  let module C = Circuit.With_interface (Contract.I) (Contract.O) in
  [ C.create_exn ~name:"self_check_contract" (Contract.hierarchical scope) ]
  |> Rtl.create Verilog
  |> Rtl.full_hierarchy
  |> Rope.to_string
;;

let rom name words =
  List.mapi words ~f:(fun a w -> sprintf "      %d: %s = 16'h%04x;" a name w)
  |> String.concat ~sep:"\n"
;;

(* teeth: a checker that takes a fall's stamp a cycle off, one that takes the next frame's
   first edge a cycle off, one that halts without its irq, and one that raises it a cycle
   late *)
let mutate source = function
  | None -> source
  | Some (pattern, with_) ->
    let mutated = String.substr_replace_first source ~pattern ~with_ in
    if String.equal mutated source then raise_s [%message "BUG: no" pattern];
    mutated
;;

let harness ~edges ~base ~mutant =
  let source = mutate (Self_check.checker ~pin ~base) mutant in
  let program = Asm.assemble source |> ok_exn in
  let config = Asm.Program.configure program (Self_check.checker_config ~pin) in
  let words = Asm.Program.words program |> ok_exn in
  let rows = Self_check.rows ~base edges |> ok_exn in
  let inner = List.drop_last_exn edges in
  let least = List.last_exn edges in
  if List.length inner > max_inner
  then raise_s [%message "more edges than the contract keeps"];
  let widths = Contract.I.port_widths in
  let config_ports =
    Engine.Config.(
      to_list
        (map2 port_names (of_program_config config) ~f:(fun name bits ->
           [%string
             ".config$%{name}(%{Bits.width bits#Int}'d%{Bits.to_unsigned_int bits#Int})"])))
    |> String.concat ~sep:",\n    "
  in
  let inner_ports =
    List.mapi widths.inner ~f:(fun n width ->
      let edge = List.nth inner n |> Option.value ~default:0 in
      [%string ".inner_%{n#Int}(%{width#Int}'d%{edge#Int})"])
    |> String.concat ~sep:", "
  in
  [%string
    {|// Generated by test/certify/write_self_check.exe: Self_check.checker on pin %{pin#Int}
// with rows at %{base#Int} for edges %{String.concat ~sep:" " (List.map edges ~f:Int.to_string)}, beside its contract. The line is free.
module self_check (input clk);
  (* anyseq *) wire [27:0] inputs;

  function [15:0] rom(input [8:0] a);
    case (a)
%{rom "rom" words}
      default: rom = 0;
    endcase
  endfunction
  function [15:0] rows(input [8:0] a);
    case (a)
%{rom "rows" (List.init base ~f:(fun _ -> 0) @ rows)}
      default: rows = 0;
    endcase
  endfunction

  reg [1:0] boot = 0;
  always @(posedge clk) if (boot != 3) boot <= boot + 1;
  wire clear = boot == 0;
  wire start = boot == 1;
  // the checker's cycle 0, as the model counts, is the first running
  wire running = boot == 3;

  wire [8:0] sram_addr, data_sram_addr;
  reg [15:0] fetched, data_word;
  always @(posedge clk) begin
    fetched <= rom(sram_addr);
    data_word <= rows(data_sram_addr);
  end
  wire irq, missed;
  engine_top dut (
    .clock(clk), .clear(clear),
    %{config_ports},
    .start(start), .program_write$valid(1'b0), .program_write$addr(9'b0),
    .program_write$data(16'b0), .data_write$valid(1'b0), .data_write$addr(9'b0),
    .data_write$data(16'b0), .tx$valid(1'b0), .tx$value(16'b0), .rx_pop(1'b0),
    .clear_irq(1'b0), .stop(1'b0), .flush(1'b0),
    .inputs(inputs), .sram_addr(sram_addr), .sram_dout(fetched),
    .data_sram_addr(data_sram_addr), .data_sram_dout(data_word),
    .irq(irq), .fault$missed_deadline(missed));

  wire violated, overdue, late;
  wire [1:0] ended;
  self_check_contract contract (
    .clock(clk), .clear(!running), .line(inputs[%{pin#Int}]),
    %{inner_ports},
    .count(%{widths.count#Int}'d%{List.length inner#Int}), .least(%{widths.least#Int}'d%{least#Int}),
    .violated(violated), .overdue(overdue), .ended(ended),
    .late(late));

  always @(*)
    if (running) begin
      assert (!irq || violated);
      assert (!overdue || irq);
      assert (!missed);
    end

  // the irq rising in the very cycle it falls due, for a break five or more before the
  // least and for one later: neither deadline is loose
  reg was_irq = 0;
  always @(posedge clk) was_irq <= irq;
  wire due_now = overdue && irq && !was_irq;
  always @(posedge clk) begin
    cover (running && irq);
    cover (running && due_now && !late);
    cover (running && due_now && late);
    // two clean frames, the second anchored where the first left off
    cover (running && ended == 2 && !violated);
  end
endmodule

%{contract_verilog ()}|}]
;;

let () =
  let args = Sys.get_argv () in
  let value name =
    Array.findi args ~f:(fun _ a -> String.equal a name)
    |> Option.map ~f:(fun (i, _) -> args.(i + 1))
  in
  let mutant =
    match value "-mutant" with
    | None -> None
    | Some "stamp" -> Some ("sub x, 5", "sub x, 4")
    | Some "least" -> Some ("add x, 6", "add x, 7")
    | Some "silent" -> Some ("    irq\n", "    mov x, x\n")
    | Some "slow" -> Some ("fault:\n", "fault:\n    mov x, x\n")
    | Some other -> raise_s [%message "unknown mutant" other]
  in
  let edges =
    value "-edges"
    |> Option.value_map ~default:[ 29; 46; 63; 83 ] ~f:(fun s ->
      String.split s ~on:',' |> List.map ~f:Int.of_string)
  in
  let base = value "-base" |> Option.value_map ~default:0 ~f:Int.of_string in
  print_string (harness ~edges ~base ~mutant)
;;
