open! Core
open! Hardcaml
open Protocol_emulator
open Protocol_emulator_test

(* The firmware whose certificates are checked on the RTL: each is analysed with no
   assumption about the world, so the pins and the host can do anything. *)
let firmwares =
  [ "uart_tx", Firmware.uart_tx ~period:8, Program_config.default
    (* the same UART at the slower bit period the tests use, for the deep run *)
  ; "uart_tx16", Firmware.uart_tx ~period:16, Program_config.default
  ; "spi_master", Firmware.spi_master ~half_period:8, Firmware.spi_config
  ; "ws2812", Ws2812.firmware ~third:6 ~tail:7, Ws2812.config
  ]
;;

let harness ~config source =
  let program = Asm.assemble source |> ok_exn in
  let config = Asm.Program.configure program config in
  let words = Asm.Program.words program |> ok_exn in
  let rows = Analyser.analyse ~config program.instructions in
  let n = List.length words in
  let config_ports =
    Engine.Config.(
      to_list
        (map2 port_names (of_program_config config) ~f:(fun name bits ->
           [%string
             ".config$%{name}(%{Bits.width bits#Int}'d%{Bits.to_unsigned_int bits#Int})"])))
    |> String.concat ~sep:",\n    "
  in
  let words =
    List.mapi words ~f:(fun a w -> sprintf "      %d: word = 16'h%04x;" (a + 1) w)
    |> String.concat ~sep:"\n"
  in
  let bound (row : Analyser.Row.t) =
    let side op = Option.map ~f:(fun v -> sprintf "phase %s %d" op v) in
    match List.filter_opt [ side ">=" row.phase.lo; side "<=" row.phase.hi ] with
    | [] -> None
    | sides -> Some (row.pc, String.concat ~sep:" && " sides)
  in
  let bounds = List.filter_map rows ~f:bound in
  let asserts =
    List.map bounds ~f:(fun (pc, claim) ->
      sprintf "      if (entry && pc == %d) assert (%s);" pc claim)
    |> String.concat ~sep:"\n"
  in
  let covers =
    List.map bounds ~f:(fun (pc, _) -> sprintf "    cover (entry && pc == %d);" pc)
    |> String.concat ~sep:"\n"
  in
  [%string
    {|// Generated by test/certify/write_certificate.exe: the analyser's certificate as
// properties of the RTL. The program goes in through the write port while the core is
// halted and then starts; the pins and the host's fifo traffic are free.
module certificate (input clk);
  (* anyseq *) wire tx_valid, rx_pop;
  (* anyseq *) wire [15:0] tx_value;
  (* anyseq *) wire [27:0] inputs;

  reg [9:0] boot = 0;
  always @(posedge clk) if (boot <= %{n + 1#Int}) boot <= boot + 1;
  wire clear = boot == 0;
  wire writing = boot >= 1 && boot <= %{n#Int};
  wire start = boot == %{n + 1#Int};
  reg [15:0] word;
  always @(*)
    case (boot)
%{words}
      default: word = 0;
    endcase

  wire [8:0] pc;
  wire [23:0] t, now;
  wire [4:0] stall;
  wire halted;
  engine_top dut (
    .clock(clk), .clear(clear),
    %{config_ports},
    .start(start), .program_write$valid(writing), .program_write$addr(boot - 10'd1),
    .program_write$data(word), .data_write$valid(1'b0), .data_write$addr(9'b0),
    .data_write$data(16'b0), .tx$valid(tx_valid), .tx$value(tx_value), .rx_pop(rx_pop),
    .clear_irq(1'b0), .stop(1'b0), .flush(1'b0), .resume(1'b0), .single_step(1'b0),
    .inputs(inputs), .pc(pc), .t(t), .now(now), .stall(stall), .halted(halted));

  // an instruction issues when the core runs and no delay is left; a wait that stalls
  // issues again every cycle, and only its first issue is where the analyser looks
  reg started = 0;
  always @(posedge clk) started <= start;
  wire issue = !clear && !halted && stall == 0 && !started;
  reg last_issue = 0;
  reg [8:0] last_pc = 0;
  always @(posedge clk) begin
    last_issue <= issue;
    last_pc <= pc;
  end
  wire entry = issue && !(last_issue && last_pc == pc);
  wire signed [23:0] phase = now - t;

  always @(*)
    if (!clear) begin
%{asserts}
    end

  always @(posedge clk) begin
%{covers}
  end
endmodule
|}]
;;

let () =
  let name = (Sys.get_argv ()).(1) in
  match List.find firmwares ~f:(fun (n, _, _) -> String.equal n name) with
  | None -> raise_s [%message "no such firmware" (name : string)]
  | Some (_, source, config) -> print_string (harness ~config source)
;;
