open! Core
open! Hardcaml
open Protocol_emulator
open Protocol_emulator_test

(* The firmware whose certificates are checked on the RTL: each is analysed with no
   assumption about the world, so the pins and the host can do anything. *)
let firmwares =
  [ "uart_tx", Firmware.uart_tx ~period:8, Program_config.default
    (* the same UART at the slower bit period the tests use, for the deep run *)
  ; "uart_tx16", Firmware.uart_tx ~period:16, Program_config.default
  ; "spi_master", Firmware.spi_master ~half_period:8, Firmware.spi_config
  ; "ws2812", Ws2812.firmware ~third:6 ~tail:7, Ws2812.config
  ]
;;

let harness ~config source =
  let program = Asm.assemble source |> ok_exn in
  let config = Asm.Program.configure program config in
  let words = Asm.Program.words program |> ok_exn in
  let rows = Analyser.analyse ~config program.instructions in
  let n = List.length words in
  let config_ports =
    Engine.Config.(
      to_list
        (map2 port_names (of_program_config config) ~f:(fun name bits ->
           [%string
             ".config$%{name}(%{Bits.width bits#Int}'d%{Bits.to_unsigned_int bits#Int})"])))
    |> String.concat ~sep:",\n    "
  in
  let words =
    List.mapi words ~f:(fun a w -> sprintf "      %d: word = 16'h%04x;" (a + 1) w)
    |> String.concat ~sep:"\n"
  in
  let bound (row : Analyser.Row.t) =
    let side op = Option.map ~f:(fun v -> sprintf "phase %s %d" op v) in
    match List.filter_opt [ side ">=" row.phase.lo; side "<=" row.phase.hi ] with
    | [] -> None
    | sides -> Some (row.pc, String.concat ~sep:" && " sides)
  in
  let bounds = List.filter_map rows ~f:bound in
  let asserts =
    List.map bounds ~f:(fun (pc, claim) ->
      sprintf "      if (entry && pc == %d) assert (%s);" pc claim)
    |> String.concat ~sep:"\n"
  in
  let covers =
    List.map bounds ~f:(fun (pc, _) -> sprintf "    cover (entry && pc == %d);" pc)
    |> String.concat ~sep:"\n"
  in
  [%string
    {|// Generated by test/certify/write_certificate.exe: the analyser's certificate as
// properties of the RTL. The program goes in through the write port while the core is
// halted and then starts; the pins and the host's fifo traffic are free.
module certificate (input clk);
  (* anyseq *) wire tx_valid, rx_pop;
  (* anyseq *) wire [15:0] tx_value;
  (* anyseq *) wire [27:0] inputs;

  reg [9:0] boot = 0;
  always @(posedge clk) if (boot <= %{n + 1#Int}) boot <= boot + 1;
  wire clear = boot == 0;
  wire writing = boot >= 1 && boot <= %{n#Int};
  wire start = boot == %{n + 1#Int};
  reg [15:0] word;
  always @(*)
    case (boot)
%{words}
      default: word = 0;
    endcase

  wire [8:0] pc;
  wire [23:0] t, now;
  wire [4:0] stall;
  wire halted;
  engine_top dut (
    .clock(clk), .clear(clear),
    %{config_ports},
    .start(start), .program_write$valid(writing), .program_write$addr(boot - 10'd1),
    .program_write$data(word), .data_write$valid(1'b0), .data_write$addr(9'b0),
    .data_write$data(16'b0), .tx$valid(tx_valid), .tx$value(tx_value), .rx_pop(rx_pop),
    .clear_irq(1'b0), .stop(1'b0), .flush(1'b0), .resume(1'b0), .single_step(1'b0),
    .inputs(inputs), .pc(pc), .t(t), .now(now), .stall(stall), .halted(halted));

  // an instruction issues when the core runs and no delay is left; a wait that stalls
  // issues again every cycle, and only its first issue is where the analyser looks
  reg started = 0;
  always @(posedge clk) started <= start;
  wire issue = !clear && !halted && stall == 0 && !started;
  reg last_issue = 0;
  reg [8:0] last_pc = 0;
  always @(posedge clk) begin
    last_issue <= issue;
    last_pc <= pc;
  end
  wire entry = issue && !(last_issue && last_pc == pc);
  wire signed [23:0] phase = now - t;

  always @(*)
    if (!clear) begin
%{asserts}
    end

  always @(posedge clk) begin
%{covers}
  end
endmodule
|}]
;;

(* The same certificate as an invariant for induction, which holds for all time rather
   than to a depth. The program is a ROM behind the macro's port, read a cycle late as the
   macro is, so nothing about it can be wrong in the state induction starts from. At every
   cycle the core runs:

   - the instruction register holds the word at the pc and the memory's output the word
     after it, but in the second cycle of a jump, when the output is the word at the new
     pc and the register still the jump;
   - the opcode and the decode flag, which the core registers beside the word, say what
     the word says: they are state of their own, and induction would start them
     disagreeing with it and let a wait retire before its deadline;
   - what is left of a delay brings the next issue to the phase its row allows;
   - a wait that stalls has reached its row and, on a deadline, not yet the deadline;
   - x, y and p hold what the analyser says they hold on the way into the pc. *)
let inductive ?(no_wrap = false) ~config source =
  let program = Asm.assemble source |> ok_exn in
  let config = Asm.Program.configure program config in
  let words = Asm.Program.words program |> ok_exn in
  let rows = Analyser.analyse ~config program.instructions in
  let config_ports =
    Engine.Config.(
      to_list
        (map2 port_names (of_program_config config) ~f:(fun name bits ->
           [%string
             ".config$%{name}(%{Bits.width bits#Int}'d%{Bits.to_unsigned_int bits#Int})"])))
    |> String.concat ~sep:",\n    "
  in
  let rom =
    List.mapi words ~f:(fun a w -> sprintf "      %d: rom = 16'h%04x;" a w)
    |> String.concat ~sep:"\n"
  in
  let within value (i : Interval.t) =
    List.filter_opt
      [ Option.map i.lo ~f:(fun lo -> sprintf "%s >= %d" value lo)
      ; Option.map i.hi ~f:(fun hi -> sprintf "%s <= %d" value hi)
      ]
  in
  let is_deadline_wait (t : Isa.t) =
    match t with
    | Op { op = Wait (Deadline _); _ } -> true
    | _ -> false
  in
  let claims =
    List.concat_map rows ~f:(fun (row : Analyser.Row.t) ->
      let conj = String.concat ~sep:" && " in
      let registers =
        within "x" row.x @ within "y" row.y @ within "p" row.period
        |> List.map ~f:(sprintf "      if (pc == %d) assert (%s);" row.pc)
      in
      let pending =
        match within "ahead" row.phase with
        | [] -> []
        | c -> [ sprintf "      if (pc == %d && stall != 0) assert (%s);" row.pc (conj c) ]
      in
      let entry =
        match within "phase" row.phase with
        | [] -> []
        | c -> [ sprintf "      if (pc == %d && entry) assert (%s);" row.pc (conj c) ]
      in
      let stalled =
        match row.phase.lo with
        | None -> []
        | Some lo ->
          [ sprintf
              "      if (pc == %d && stalled) assert (phase >= %d%s);"
              row.pc
              (lo + 1)
              (if is_deadline_wait row.instruction then " && phase <= 0" else "")
          ]
      in
      registers @ pending @ entry @ stalled)
    |> String.concat ~sep:"\n"
  in
  (* induction proves anything from an invariant no state satisfies, so the teeth task
     adds a claim that is false in any run and has to fail. It names the last row, which
     no run reaches inside the base case's depth, so what fails is the induction step and
     the failure says the invariant is one some state satisfies. *)
  let teeth_pc = (List.last_exn rows).pc in
  (* The only thing a certificate ever assumes of the world. A loop that anchors no
     deadline has no floor under its phase: intervals cannot say that the loop's counter
     runs out, so the analyser lets the core fall arbitrarily far behind its deadline and
     24 bits of the difference wrap. The core's own release compares the same 24 bits, so
     this is a bound the hardware keeps as well: a deadline older than about 168 ms at
     50 MHz is a deadline it reads the wrong way round. *)
  let no_wrap =
    if not no_wrap
    then ""
    else
      "  // the certificate of a loop that anchors no deadline holds while the core is\n\
      \  // within 84 ms of it, which is the half of what its 24 bits can tell apart\n\
      \  always @(*) assume (phase >= -24'sd4194304 && phase <= 24'sd4194304);\n\n"
  in
  let wrap_top = config.wrap_top in
  let wrap_bottom = config.wrap_bottom in
  [%string
    {|// Generated by test/certify/write_certificate.exe -inductive: the analyser's certificate
// as an invariant of the RTL, for every input and every host, proved by induction.
module certificate (input clk);
  (* anyseq *) wire tx_valid, rx_pop;
  (* anyseq *) wire [15:0] tx_value;
  (* anyseq *) wire [27:0] inputs;

  function [15:0] rom(input [8:0] a);
    case (a)
%{rom}
      default: rom = 0;
    endcase
  endfunction
  function [8:0] after(input [8:0] a);
    after = a == %{wrap_top#Int} ? %{wrap_bottom#Int} : a + 9'd1;
  endfunction

  reg [1:0] boot = 0;
  always @(posedge clk) if (boot != 3) boot <= boot + 1;
  wire clear = boot == 0;
  wire start = boot == 1;
  wire running = boot == 3;

  wire [8:0] sram_addr, pc;
  reg [15:0] fetched;
  always @(posedge clk) fetched <= rom(sram_addr);
  wire [23:0] t, now;
  wire [15:0] x, y, p, instruction;
  wire [7:0] opcode_onehot;
  wire [4:0] stall;
  wire halted, stepping, decode_ok, eng_issue, eng_jmp_go;
  engine_top dut (
    .clock(clk), .clear(clear),
    %{config_ports},
    .start(start), .program_write$valid(1'b0), .program_write$addr(9'b0),
    .program_write$data(16'b0), .data_write$valid(1'b0), .data_write$addr(9'b0),
    .data_write$data(16'b0), .tx$valid(tx_valid), .tx$value(tx_value), .rx_pop(rx_pop),
    .clear_irq(1'b0), .stop(1'b0), .flush(1'b0), .resume(1'b0), .single_step(1'b0),
    .inputs(inputs), .sram_addr(sram_addr), .sram_dout(fetched), .data_sram_dout(16'b0),
    .pc(pc), .t(t), .now(now), .x(x), .y(y), .p(p), .stall(stall), .halted(halted),
    .stepping(stepping), .instruction(instruction), .decode_ok(decode_ok),
    .opcode_onehot(opcode_onehot), .eng_issue(eng_issue), .eng_jmp_go(eng_jmp_go));

  // the engine's own signals, not a shadow of them worked out from the delay left: in the
  // state induction starts from the two come apart
  reg started = 0;
  always @(posedge clk) started <= start;
  wire issue = running && eng_issue && !started;
  // the second cycle of a jump: the core took one and is fetching at the target
  reg jumped = 0;
  always @(posedge clk) jumped <= start || eng_jmp_go;
  reg last_issue = 0;
  reg [8:0] last_pc = 0;
  always @(posedge clk) begin
    last_issue <= issue;
    last_pc <= pc;
  end
  wire entry = issue && !(last_issue && last_pc == pc);
  wire stalled = issue && last_issue && last_pc == pc;
  wire signed [23:0] phase = now - t;
  // the phase the pending instruction issues at, once the delay runs out
  wire signed [23:0] ahead = now - t + {19'b0, stall};

%{no_wrap}  always @(*)
    if (running) begin
      assert (!halted && !stepping && !started);
      assert (decode_ok && opcode_onehot == (8'd1 << instruction[15:13]));
      if (!jumped) assert (instruction == rom(pc) && fetched == rom(after(pc)));
      if (jumped) assert (stall == 1 && fetched == rom(pc));
      if (stalled) assert (instruction[15:13] == 1);
%{claims}
`ifdef TEETH
      assert (pc != %{teeth_pc#Int});
`endif
    end
endmodule
|}]
;;

let () =
  let args = Sys.get_argv () in
  let inductive_mode = Array.exists args ~f:(String.equal "-inductive") in
  let no_wrap = Array.exists args ~f:(String.equal "-no-wrap") in
  let name = Array.last_exn args in
  match List.find firmwares ~f:(fun (n, _, _) -> String.equal n name) with
  | None -> raise_s [%message "no such firmware" (name : string)]
  | Some (_, source, config) ->
    print_string
      (if inductive_mode then inductive ~no_wrap ~config source else harness ~config source)
;;
