open! Core
open! Hardcaml
open Protocol_emulator
open Protocol_emulator_test

let harness ~config source =
  let program = Asm.assemble source |> ok_exn in
  let config = Asm.Program.configure program config in
  let words = Asm.Program.words program |> ok_exn in
  let rows = Analyser.analyse ~config program.instructions in
  let n = List.length words in
  let config_ports =
    Engine.Config.(
      to_list
        (map2 port_names (of_program_config config) ~f:(fun name bits ->
           [%string
             ".config$%{name}(%{Bits.width bits#Int}'d%{Bits.to_unsigned_int bits#Int})"])))
    |> String.concat ~sep:",\n    "
  in
  let words =
    List.mapi words ~f:(fun a w -> sprintf "      %d: word = 16'h%04x;" (a + 1) w)
    |> String.concat ~sep:"\n"
  in
  let bound (row : Analyser.Row.t) =
    let side op = Option.map ~f:(fun v -> sprintf "phase %s %d" op v) in
    match List.filter_opt [ side ">=" row.phase.lo; side "<=" row.phase.hi ] with
    | [] -> None
    | sides -> Some (row.pc, String.concat ~sep:" && " sides)
  in
  let bounds = List.filter_map rows ~f:bound in
  let asserts =
    List.map bounds ~f:(fun (pc, claim) ->
      sprintf "      if (entry && pc == %d) assert (%s);" pc claim)
    |> String.concat ~sep:"\n"
  in
  let covers =
    List.map bounds ~f:(fun (pc, _) -> sprintf "    cover (entry && pc == %d);" pc)
    |> String.concat ~sep:"\n"
  in
  [%string
    {|// Generated by test/certify/write_certificate.exe: the analyser's certificate as
// properties of the RTL. The program goes in through the write port while the core is
// halted and then starts; the pins and the host's fifo traffic are free.
module certificate (input clk);
  (* anyseq *) wire tx_valid, rx_pop;
  (* anyseq *) wire [15:0] tx_value;
  (* anyseq *) wire [27:0] inputs;

  reg [9:0] boot = 0;
  always @(posedge clk) if (boot <= %{n + 1#Int}) boot <= boot + 1;
  wire clear = boot == 0;
  wire writing = boot >= 1 && boot <= %{n#Int};
  wire start = boot == %{n + 1#Int};
  reg [15:0] word;
  always @(*)
    case (boot)
%{words}
      default: word = 0;
    endcase

  wire [8:0] pc;
  wire [23:0] t, now;
  wire [4:0] stall;
  wire halted;
  engine_top dut (
    .clock(clk), .clear(clear),
    %{config_ports},
    .start(start), .program_write$valid(writing), .program_write$addr(boot - 10'd1),
    .program_write$data(word), .data_write$valid(1'b0), .data_write$addr(9'b0),
    .data_write$data(16'b0), .tx$valid(tx_valid), .tx$value(tx_value), .rx_pop(rx_pop),
    .clear_irq(1'b0), .stop(1'b0), .flush(1'b0), .resume(1'b0), .single_step(1'b0),
    .inputs(inputs), .pc(pc), .t(t), .now(now), .stall(stall), .halted(halted));

  // an instruction issues when the core runs and no delay is left; a wait that stalls
  // issues again every cycle, and only its first issue is where the analyser looks
  reg started = 0;
  always @(posedge clk) started <= start;
  wire issue = !clear && !halted && stall == 0 && !started;
  reg last_issue = 0;
  reg [8:0] last_pc = 0;
  always @(posedge clk) begin
    last_issue <= issue;
    last_pc <= pc;
  end
  wire entry = issue && !(last_issue && last_pc == pc);
  wire signed [23:0] phase = now - t;

  always @(*)
    if (!clear) begin
%{asserts}
    end

  always @(posedge clk) begin
%{covers}
  end
endmodule
|}]
;;

let writes_pins (t : Isa.t) =
  match t with
  | Op
      { op =
          ( Set { dest = Pins | Pindirs; _ }
          | Out { dest = Pins | Pindirs; _ }
          | Mov { dest = Pins | Pindirs; _ } )
      ; _
      } -> true
  | _ -> false
;;

(* The departure time in a stamped frame, for a transmitter shaped like
   [Firmware.uart_tx_stamped]: [mov y, now] starts the stamp, a [set pins, 0] sends the
   start bit, [mov osr, y] loads the stamp and [wait t+; out pins, 1; jmp x--] sends it
   LSB first. The claims:

   - in the first cycle the start bit shows, the line was high the cycle before and [y]
     holds the low 16 bits of [now];
   - [y] keeps that stamp until [mov osr, y], and the bits of [osr] still to go are the
     stamp's, from the next one to send;
   - from each [out] to the next, the pin shows the stamp bit it sent.

   What makes the first inductive is the line's level where the program knows it, since
   every instruction after a [set pins] finds the level it set up to the next pin write,
   and the delay left at each pc, which is no more than its ways in leave.

   It assumes no more than the certificate: inputs and the host's fifo traffic are free,
   and the host never halts the core. No bound on the clock is needed, since the stamp is
   [now] modulo 2^16 and so wraps with it; a receiver that wants the whole cycle unwraps
   it, which takes frames less than 65536 cycles apart or a count of its own. The pin is
   the engine's [pin_out] register, and each flop between it and the pad adds one cycle.

   Two claims made wrong on purpose have to fail: OFF_BY_ONE puts the stamp a cycle after
   the edge, which a run from reset contradicts, and NEXT_BIT says the pin shows the bit
   after the one sent, which the invariant must not imply. *)
let stamp_claims ~(config : Program_config.t) (rows : Analyser.Row.t list) =
  if config.side_set_count <> 0
     || config.manchester
     || config.set_base <> config.out_base
     || not (Program_config.Shift_direction.equal config.out_shift Right)
  then raise_s [%message "BUG: a stamped frame goes out on one plain pin, LSB first"];
  let find ?(after = -1) what ~f =
    match List.find rows ~f:(fun row -> row.pc > after && f row.instruction) with
    | Some row -> row.pc
    | None -> raise_s [%message "BUG: not a stamped transmitter" (what : string)]
  in
  let read_now =
    find "mov y, now" ~f:(function
      | Op { op = Mov { dest = Y; op = Copy; source = Now }; _ } -> true
      | _ -> false)
  in
  let start =
    find "start bit" ~after:read_now ~f:(function
      | Op { op = Set { dest = Pins; value = 0 }; _ } -> true
      | _ -> false)
  in
  let load =
    find "mov osr, y" ~after:start ~f:(function
      | Op { op = Mov { dest = Osr; op = Copy; source = Y }; _ } -> true
      | _ -> false)
  in
  let shift =
    find "out pins, 1" ~after:load ~f:(function
      | Op { op = Out { dest = Pins; count = 1 }; _ } -> true
      | _ -> false)
  in
  let wait = shift - 1 in
  let jmp = shift + 1 in
  let instruction pc = (List.nth_exn rows pc).instruction in
  (match instruction (load + 1), instruction wait, instruction jmp with
   | ( Op { op = Set { dest = X; value = 15 }; _ }
     , Op { op = Wait (Deadline { advance = true }); _ }
     , Jmp { cond = X_dec; target } )
     when wait = load + 2 && target = wait -> ()
   | _ -> raise_s [%message "BUG: the stamp is not sent as sixteen bits"]);
  (* the level each pc finds the line at, where every way in agrees; [None] is unknown *)
  let level_after (row : Analyser.Row.t) level_in =
    match row.instruction with
    | Op { op = Set { dest = Pins; value }; _ } -> Some (value land 1)
    | i when writes_pins i -> None
    | _ -> level_in
  in
  let rec settle levels =
    let next =
      List.fold rows ~init:levels ~f:(fun levels (row : Analyser.Row.t) ->
        (* the start is a way in to pc 0 at a level nothing set *)
        let start = if row.pc = 0 then [ None ] else [] in
        let ways_in =
          start
          @ List.filter_map row.since_edge ~f:(fun (from, _) ->
            Map.find levels from |> Option.map ~f:(level_after (List.nth_exn rows from)))
        in
        match ways_in with
        | [] -> levels
        | first :: rest ->
          let data =
            if List.for_all rest ~f:([%equal: int option] first) then first else None
          in
          Map.set levels ~key:row.pc ~data)
    in
    if Map.equal [%equal: int option] next levels then levels else settle next
  in
  let levels =
    settle Int.Map.empty
    |> Map.to_alist
    |> List.filter_map ~f:(fun (pc, level) ->
      Option.map level ~f:(fun level ->
        sprintf
          "      if (pc == %d%s) assert (tx == %d);"
          pc
          (if writes_pins (instruction pc) then " && entry" else "")
          level))
    |> String.concat ~sep:"\n"
  in
  (* without this induction holds the start bit back with a delay nothing left it *)
  let delays =
    List.map rows ~f:(fun (row : Analyser.Row.t) ->
      let left (from : int) =
        match instruction from with
        | Jmp _ -> Isa.jmp_cycles - 1
        | Op { delay; _ } -> delay
      in
      List.map row.since_edge ~f:(fun (from, _) -> left from)
      |> List.max_elt ~compare
      |> Option.value ~default:0
      |> sprintf "      if (pc == %d && !jumped) assert (stall <= %d);" row.pc)
    |> String.concat ~sep:"\n"
  in
  let tx_pin = config.out_base in
  let monitor =
    [%string
      {|  // the stamp: the low 16 bits of the cycle the start bit first shows
  wire tx = pin_out[%{tx_pin#Int}];
  reg last_tx = 0;
  reg shown = 0;
  reg [15:0] stamp = 0;
  always @(posedge clk) begin
    last_tx <= tx;
    shown <= entry && pc == %{start#Int};
    if (shown) stamp <= now[15:0];
  end
  // the stamp bits sent at the out and at the jump after it
  wire [4:0] sent_at_out = 5'd15 - x[4:0];
  wire [4:0] sent_at_jmp = 5'd16 - x[4:0];

|}]
  in
  let claims =
    [%string
      {|      // the delay left where the program can leave one
%{delays}
      // the line where the program knows it
%{levels}
      // the stamp is the cycle the start bit shows, and the line fell there
`ifdef OFF_BY_ONE
      if (shown) assert (y == now[15:0] + 16'd1);
`else
      if (shown) assert (!tx && last_tx && y == now[15:0]);
`endif
      if (!shown && pc > %{start#Int} && pc <= %{load#Int}) assert (y == stamp);
      if (pc == %{load + 1#Int}) assert (osr == stamp);
      if (pc == %{wait#Int} || pc == %{shift#Int})
        assert (x <= 15 && ((osr ^ (stamp >> sent_at_out)) & (16'hffff >> sent_at_out)) == 0);
      if (pc == %{jmp#Int})
        assert (x <= 15 && ((osr ^ (stamp >> sent_at_jmp)) & (16'hffff >> sent_at_jmp)) == 0);
      // and the pin shows each bit from its out to the next
      if (pc == %{jmp#Int}) assert (tx == stamp[4'd15 - x[3:0]]);
      if ((pc == %{wait#Int} || pc == %{shift#Int}) && x != 15) assert (tx == stamp[4'd14 - x[3:0]]);
      if (pc == %{jmp + 1#Int}) assert (tx == stamp[15]);
`ifdef NEXT_BIT
      if (pc == %{jmp#Int} && x != 0) assert (tx == stamp[4'd16 - x[3:0]]);
`endif
|}]
  in
  monitor, claims
;;

(* The same certificate as an invariant for induction, which holds for all time rather
   than to a depth. The program is a ROM behind the macro's port, read a cycle late as the
   macro is, so nothing about it can be wrong in the state induction starts from. At every
   cycle the core runs:

   - the instruction register holds the word at the pc and the memory's output the word
     after it, but in the second cycle of a jump, when the output is the word at the new
     pc and the register still the jump;
   - the opcode, the decode flag and the wait pin, which the core registers beside the
     word, say what the word says: they are state of their own, and induction would start
     them disagreeing with it and let a wait retire before its deadline;
   - what is left of a delay brings the next issue to the phase its row allows;
   - a wait that stalls has reached its row and, on a deadline, not yet the deadline;
   - x, y and p hold what the analyser says they hold on the way into the pc;
   - the pc is one the analyser reaches, and the instruction that issued last is one it
     says the pc can follow;
   - a Manchester bit's second half is pending only where the analyser says it can be;
   - where the program reads the capture, the captured edge is a cycle that has passed,
     which is what the analyser takes [mov t, capture] to load; the clock and the capture
     start together at zero and the clock has moved on by the first issue;
   - the cycles since the last pin edge are what the analyser says for the way in from
     that instruction, on the way in and while a delay or a wait holds the core, which is
     what makes the gaps between edges hold in a loop that anchors no deadline. *)
let inductive ?(no_wrap = false) ?(stamped = false) ~config source =
  let program = Asm.assemble source |> ok_exn in
  let config = Asm.Program.configure program config in
  let words = Asm.Program.words program |> ok_exn in
  let rows = Analyser.analyse ~config program.instructions in
  let config_ports =
    Engine.Config.(
      to_list
        (map2 port_names (of_program_config config) ~f:(fun name bits ->
           [%string
             ".config$%{name}(%{Bits.width bits#Int}'d%{Bits.to_unsigned_int bits#Int})"])))
    |> String.concat ~sep:",\n    "
  in
  let rom =
    List.mapi words ~f:(fun a w -> sprintf "      %d: rom = 16'h%04x;" a w)
    |> String.concat ~sep:"\n"
  in
  let within value (i : Interval.t) =
    List.filter_opt
      [ Option.map i.lo ~f:(fun lo -> sprintf "%s >= %d" value lo)
      ; Option.map i.hi ~f:(fun hi -> sprintf "%s <= %d" value hi)
      ]
  in
  let is_deadline_wait (t : Isa.t) =
    match t with
    | Op { op = Wait (Deadline _); _ } -> true
    | _ -> false
  in
  let is_wait (t : Isa.t) =
    match t with
    | Op { op = Wait _; _ } -> true
    | _ -> false
  in
  let any = function
    | [] -> "0"
    | cases -> String.concat ~sep:" || " cases
  in
  let reads_capture (t : Isa.t) =
    match t with
    | Op { op = Mov { source = Capture; _ } | In { source = Capture; _ }; _ } -> true
    | _ -> false
  in
  let anchors_on_capture =
    List.exists rows ~f:(fun row -> reads_capture row.instruction)
  in
  let captured_has_passed =
    if not anchors_on_capture
    then ""
    else "      assert ($signed(now - capture) >= (came_valid ? 24'sd1 : 24'sd0));\n"
  in
  let pin_writers =
    List.filter_map rows ~f:(fun row ->
      Option.some_if (writes_pins row.instruction) (sprintf "a == %d" row.pc))
    |> any
  in
  (* a count is unsigned, so a floor at or below zero says nothing and is left out *)
  let count (i : Interval.t) = { i with lo = Option.filter i.lo ~f:(fun lo -> lo > 0) } in
  let reachable = List.map rows ~f:(fun row -> sprintf "pc == %d" row.pc) |> any in
  let edges =
    List.concat_map rows ~f:(fun (row : Analyser.Row.t) ->
      let conj = String.concat ~sep:" && " in
      let came_from =
        List.map row.since_edge ~f:(fun (from, _) -> sprintf "came == %d" from)
      in
      let ways_in =
        [ sprintf
            "      if (came_valid && !stalled && pc == %d) assert (%s);"
            row.pc
            (any came_from)
        ]
      in
      let per_way =
        List.concat_map row.since_edge ~f:(fun (from, since) ->
          let at_entry =
            match within "since" (count since) with
            | [] -> []
            | c ->
              [ sprintf
                  "      if (entry && came_valid && pc == %d && came == %d) assert (%s);"
                  row.pc
                  from
                  (conj c)
              ]
          in
          let pending =
            match within "since_ahead" (count since) with
            | [] -> []
            | c ->
              [ sprintf
                  "      if (stall != 0 && came_valid && pc == %d && came == %d) assert \
                   (%s);"
                  row.pc
                  from
                  (conj c)
              ]
          in
          at_entry @ pending)
      in
      let gaps =
        List.map row.gaps ~f:(fun (from, gap) -> from, within "since + 1" (count gap))
        |> List.filter_map ~f:(fun (from, c) ->
          Option.some_if (not (List.is_empty c)) (from, c))
        |> List.map ~f:(fun (from, c) ->
          sprintf
            "      if (entry && came_valid && pc == %d && came == %d) assert (%s);"
            row.pc
            from
            (conj c))
      in
      (* while a wait stalls the count runs on from its entry, which a Manchester flip the
         wait brings starts again *)
      let stalled =
        if not (is_wait row.instruction)
        then []
        else (
          let since =
            List.map row.since_edge ~f:snd
            |> List.reduce ~f:Interval.join
            |> Option.value ~default:Interval.top
          in
          let since =
            if Option.is_some row.flip
            then Interval.join since (Interval.exactly (-1))
            else since
          in
          let floor =
            Option.filter since.lo ~f:(fun lo -> lo + 1 > 0)
            |> Option.map ~f:(fun lo ->
              sprintf
                "      if (stalled && pc == %d) assert (since >= %d);"
                row.pc
                (lo + 1))
            |> Option.to_list
          in
          let behind =
            if not (is_deadline_wait row.instruction)
            then []
            else (
              let bound lo hi =
                Option.bind lo ~f:(fun a -> Option.map hi ~f:(fun b -> a - b))
              in
              match
                within
                  "since_behind"
                  { lo = bound since.lo row.phase.hi; hi = bound since.hi row.phase.lo }
              with
              | [] -> []
              | c ->
                [ sprintf "      if (stalled && pc == %d) assert (%s);" row.pc (conj c) ])
          in
          floor @ behind)
      in
      (* only the instruction after a Manchester out finds its second half pending *)
      let flip =
        if Option.is_some row.flip
        then []
        else [ sprintf "      if (pc == %d) assert (!flip_pending);" row.pc ]
      in
      ways_in @ flip @ per_way @ gaps @ stalled)
    |> String.concat ~sep:"\n"
  in
  let claims =
    List.concat_map rows ~f:(fun (row : Analyser.Row.t) ->
      let conj = String.concat ~sep:" && " in
      let registers =
        within "x" row.x @ within "y" row.y @ within "p" row.period
        |> List.map ~f:(sprintf "      if (pc == %d) assert (%s);" row.pc)
      in
      let pending =
        match within "ahead" row.phase with
        | [] -> []
        | c ->
          [ sprintf "      if (pc == %d && stall != 0) assert (%s);" row.pc (conj c) ]
      in
      let entry =
        match within "phase" row.phase with
        | [] -> []
        | c -> [ sprintf "      if (pc == %d && entry) assert (%s);" row.pc (conj c) ]
      in
      let stalled =
        match row.phase.lo with
        | None -> []
        | Some lo ->
          [ sprintf
              "      if (pc == %d && stalled) assert (phase >= %d%s);"
              row.pc
              (lo + 1)
              (if is_deadline_wait row.instruction then " && phase <= 0" else "")
          ]
      in
      registers @ pending @ entry @ stalled)
    |> String.concat ~sep:"\n"
  in
  (* induction proves anything from an invariant no state satisfies, so the teeth task
     adds a claim that is false in any run and has to fail. It names the last row, which
     no run reaches inside the base case's depth, so what fails is the induction step and
     the failure says the invariant is one some state satisfies. *)
  let teeth_pc = (List.last_exn rows).pc in
  (* The only thing a certificate ever assumes of the world. A loop that anchors no
     deadline has no floor under its phase: intervals cannot say that the loop's counter
     runs out, so the analyser lets the core fall arbitrarily far behind its deadline and
     24 bits of the difference wrap. The core's own release compares the same 24 bits, so
     this is a bound the hardware keeps as well: a deadline older than about 168 ms at 50
     MHz is a deadline it reads the wrong way round. A wait for the host or for a pin can
     stall for as long, and the captured edge a receiver anchors on can lie as far back on
     a line that stays idle, so the same window covers those. *)
  let no_wrap =
    if not no_wrap
    then ""
    else
      "  // the certificate of a loop that anchors no deadline holds while the core is\n\
      \  // within 84 ms of it, which is the half of what its 24 bits can tell apart\n\
      \  always @(*) assume (phase >= -24'sd4194304 && phase <= 24'sd4194304);\n"
      ^ (if not anchors_on_capture
         then ""
         else
           "  // and as far from the edge it last captured\n\
           \  always @(*) assume ($signed(now - capture) <= 24'sd4194304);\n")
      ^ "\n"
  in
  let stamp_monitor, stamp_claims =
    if stamped then stamp_claims ~config rows else "", ""
  in
  let wrap_top = config.wrap_top in
  let wrap_bottom = config.wrap_bottom in
  [%string
    {|// Generated by test/certify/write_certificate.exe -inductive: the analyser's certificate
// as an invariant of the RTL, for every input and every host, proved by induction.
module certificate (input clk);
  (* anyseq *) wire tx_valid, rx_pop;
  (* anyseq *) wire [15:0] tx_value;
  (* anyseq *) wire [27:0] inputs;

  function [15:0] rom(input [8:0] a);
    case (a)
%{rom}
      default: rom = 0;
    endcase
  endfunction
  function [8:0] after(input [8:0] a);
    after = a == %{wrap_top#Int} ? %{wrap_bottom#Int} : a + 9'd1;
  endfunction

  reg [1:0] boot = 0;
  always @(posedge clk) if (boot != 3) boot <= boot + 1;
  wire clear = boot == 0;
  wire start = boot == 1;
  wire running = boot == 3;

  function writes_pins(input [8:0] a);
    writes_pins = %{pin_writers};
  endfunction

  wire [8:0] sram_addr, pc;
  reg [15:0] fetched;
  always @(posedge clk) fetched <= rom(sram_addr);
  wire [23:0] t, now, capture;
  wire [15:0] x, y, p, osr, instruction;
  wire [27:0] pin_out;
  wire [7:0] opcode_onehot;
  wire [27:0] wait_select;
  wire [27:0] wait_pin = 28'd1 << instruction[4:0];
  wire [4:0] stall;
  wire halted, stepping, decode_ok, eng_issue, eng_jmp_go, flip_pending;
  engine_top dut (
    .clock(clk), .clear(clear),
    %{config_ports},
    .start(start), .program_write$valid(1'b0), .program_write$addr(9'b0),
    .program_write$data(16'b0), .data_write$valid(1'b0), .data_write$addr(9'b0),
    .data_write$data(16'b0), .tx$valid(tx_valid), .tx$value(tx_value), .rx_pop(rx_pop),
    .clear_irq(1'b0), .stop(1'b0), .flush(1'b0), .resume(1'b0), .single_step(1'b0),
    .inputs(inputs), .sram_addr(sram_addr), .sram_dout(fetched), .data_sram_dout(16'b0),
    .pin_out(pin_out), .pc(pc), .t(t), .now(now), .capture(capture), .x(x), .y(y), .p(p),
    .osr(osr), .stall(stall),
    .halted(halted),
    .stepping(stepping), .instruction(instruction), .decode_ok(decode_ok),
    .opcode_onehot(opcode_onehot), .wait_select(wait_select), .flip_pending(flip_pending),
    .eng_issue(eng_issue),
    .eng_jmp_go(eng_jmp_go));

  // the engine's own signals, not a shadow of them worked out from the delay left: in the
  // state induction starts from the two come apart
  reg started = 0;
  always @(posedge clk) started <= start;
  wire issue = running && eng_issue && !started;
  // the second cycle of a jump: the core took one and is fetching at the target
  reg jumped = 0;
  always @(posedge clk) jumped <= start || eng_jmp_go;
  reg last_issue = 0;
  reg [8:0] last_pc = 0;
  always @(posedge clk) begin
    last_issue <= issue;
    last_pc <= pc;
  end
  wire entry = issue && !(last_issue && last_pc == pc);
  wire stalled = issue && last_issue && last_pc == pc;
  wire signed [23:0] phase = now - t;
  // the phase the pending instruction issues at, once the delay runs out
  wire signed [23:0] ahead = now - t + {19'b0, stall};

  // cycles since the last pin edge showed, which is the cycle after a pin write issues
  // or the instruction after a Manchester out, whose second half comes with it
  wire edge_now = issue && (writes_pins(pc) || flip_pending);
  reg [23:0] since = 0;
  always @(posedge clk) since <= edge_now ? 24'd0 : since == 24'hffffff ? since : since + 1;
  wire [24:0] since_ahead = since + stall;
  wire signed [25:0] since_behind = $signed({2'b0, since}) - phase;
  // the instruction that issued last, the one the analyser calls the way in
  reg came_valid = 0;
  reg [8:0] came = 0;
  always @(posedge clk)
    if (start) came_valid <= 0;
    else if (entry) begin
      came_valid <= 1;
      came <= pc;
    end

%{stamp_monitor}%{no_wrap}  always @(*)
    if (running) begin
      assert (!halted && !stepping && !started);
%{captured_has_passed}      assert (decode_ok && opcode_onehot == (8'd1 << instruction[15:13]));
      assert (wait_select == wait_pin);
      if (!jumped) assert (instruction == rom(pc) && fetched == rom(after(pc)));
      if (jumped) assert (stall == 1 && fetched == rom(pc));
      if (stalled) assert (instruction[15:13] == 1);
      assert (%{reachable});
      // until the first issue after the start, nothing has issued to come from
      if (!came_valid) assert (pc == 0 && stall == 0);
      // and a wait that stalls came last itself
      if (stalled) assert (came_valid && came == pc);
%{claims}
%{edges}
%{stamp_claims}`ifdef TEETH
      assert (pc != %{teeth_pc#Int});
`endif
    end
endmodule
|}]
;;

let () =
  let args = Sys.get_argv () in
  let inductive_mode = Array.exists args ~f:(String.equal "-inductive") in
  let stamped = Array.exists args ~f:(String.equal "-stamped") in
  let { Certified.source; config; no_wrap; _ } =
    Certified.find_exn (Array.last_exn args)
  in
  print_string
    (if inductive_mode
     then inductive ~no_wrap ~stamped ~config source
     else harness ~config source)
;;
