(executable
 (name write_trace)
 (libraries core protocol_emulator_test)
 (preprocess
  (pps ppx_jane)))

;; the rules for each scenario's trace, from Pin_scenarios.all
(include dune.inc)

(rule
 (with-stdout-to
  dune.inc.gen
  (run ./write_trace.exe -dune)))

(rule
 (alias runtest)
 (action
  (diff dune.inc dune.inc.gen)))
