name: ocaml
on: [push, workflow_dispatch]
jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6

      - name: Set up OxCaml
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: ocaml-variants.5.2.0+ox
          opam-repositories: |
            ox: https://github.com/oxcaml/opam-repository.git
            default: https://opam.ocaml.org

      - name: Install dependencies
        run: |
          sudo apt-get install -y z3
          opam install . --deps-only --with-test --locked

      - name: Run tests
        run: opam exec -- dune build @runtest

      - name: Install OSS CAD Suite
        run: |
          curl -sL https://github.com/YosysHQ/oss-cad-suite-build/releases/download/2026-09-16/oss-cad-suite-linux-x64-20260916.tgz | tar xz -C "$HOME"
          echo "$HOME/oss-cad-suite/bin" >> "$GITHUB_PATH"

      - name: Prove
        run: |
          opam exec -- dune exec -- bin/generate.exe engine > formal/engine.v
          opam exec -- dune exec -- bin/generate.exe engine -sram > formal/engine_sram.v
          make -C formal issue_timing host_timing
